version: "3.8"
services:
    app:
        build:
            args:
                user: MP
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: alopeyk
        container_name: app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - net
        depends_on:
            - db
            - redis

    db:
        image: mysql:latest
        container_name: db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./docker/mysql:/docker-entrypoint-initdb.d
        networks:
            - net

    redis:
        image: redis:latest
        container_name: redis
        restart: unless-stopped
        networks:
            - net

    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx:/etc/nginx/conf.d/
        networks:
            - net

networks:
    net:
        driver: bridge
